---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodns-deployment
  namespace: autodns
  labels:
    app: autodns
spec:
  selector:
    matchLabels:
      app: autodns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: autodns
    spec:
      containers:
      - image: lukegriffith/autodns
        name: autodns
        env:
        - name: zone_name
          value: griffith.cloud
        - name: a_record
          value: home
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: autodns-aws-role
              key: ACCESS_KEY
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: autodns-aws-role
              key: SECRET_ACCESS_KEY

